export type Language = 'fr' | 'en';

export type TranslationDictionary = {
	common: {
		yes: string;
		no: string;
		save: string;
		cancel: string;
		delete: string;
		edit: string;
		view: string;
		actions: string;
		add: string;
		back: string;
		update: string;
		confirm: string;
		search: string;
		loading: string;
		refresh: string;
		retry: string;
		submit: string;
		close: string;
		display: string;
		selectValue: string;
		filterBy: string;
		dashboard: string;
		skipToContent: string;
		newItem: string;
		addImage: string;
		clickToEditCrop: string;
		noOptions: string;
		all: string;
		value: string;
		clearSelection: string;
		allMatchingSelected: (n: number) => string;
		pageElementsSelected: (n: number) => string;
		selectAllMatching: (n: number) => string;
		activeFiltersCount: (n: number) => string;
		validationErrorsDetected: string;
		appLogo: string;
		croppedPreview: string;
		togglePasswordVisibility: string;
		project: string;
		category: string;
		amount: string;
		date: string;
		notes: string;
		description: string;
		createdBy: string;
		total: string;
		status: string;
		name: string;
		dateCreated: string;
	};
	filters: {
		contains: string;
		equals: string;
		startsWith: string;
		endsWith: string;
		isEmpty: string;
		isNotEmpty: string;
		is: string;
		between: string;
		from: string;
		to: string;
		addFilter: string;
		removeAllFilters: string;
		and: string;
		or: string;
		allUsers: string;
	};
	navigation: {
		users: string;
		usersList: string;
		newUser: string;
		settings: string;
		myProfile: string;
		changePassword: string;
		logout: string;
		administration: string;
		welcomeMale: string;
		welcomeFemale: string;
		welcomeNeutral: string;
		projects: string;
		projectsList: string;
		newProject: string;
		categories: string;
		categoriesList: string;
		newCategory: string;
		revenues: string;
		revenuesList: string;
		newRevenue: string;
		expenses: string;
		expensesList: string;
		newExpense: string;
		dashboard: string;
		viewDashboard: string;
		notifications: string;
		notificationPreferences: string;
		markAllRead: string;
		noNotifications: string;
		loadMore: string;
	};
	users: {
		firstName: string;
		lastName: string;
		email: string;
		gender: string;
		admin: string;
		active: string;
		inactive: string;
		registrationDate: string;
		lastUpdate: string;
		lastLogin: string;
		canView: string;
		canPrint: string;
		canCreate: string;
		canEdit: string;
		canDelete: string;
		deleteUser: string;
		deleteUserConfirm: string;
		addUser: string;
		updateUser: string;
		createUser: string;
		editUser: string;
		userDetails: string;
		avatar: string;
		profilePhoto: string;
		newUser: string;
		personalInfo: string;
		accountSettings: string;
		permissions: string;
		activeAccount: string;
		adminAccount: string;
		deleteUsers: (n: number) => string;
		male: string;
		female: string;
		userDeletedSuccess: string;
		userDeleteError: string;
		bulkDeleteUserBody: (n: number) => string;
		bulkUserDeletedSuccess: (n: number) => string;
		generalInfo: string;
		userNotFound: string;
		userUpdatedSuccess: string;
		userCreatedSuccess: string;
		userUpdateError: string;
		userCreateError: string;
		avatarCropped: string;
		validationErrorsDetected: string;
		fixValidationErrors: string;
	};
	settings: {
		profile: string;
		editProfile: string;
		changePassword: string;
		oldPassword: string;
		newPassword: string;
		confirmNewPassword: string;
		defaultPasswordWarning: string;
		modify: string;
		updateSuccess: string;
		updateError: string;
		passwordChangeSuccess: string;
		passwordChangeError: string;
		notificationPreferences: string;
		notificationUpdateSuccess: string;
		notificationUpdateError: string;
		notifyBudgetOverrun: string;
		notifyBudgetThreshold: string;
		notifyDeadlineApproaching: string;
		notifyProjectOverdue: string;
		notifyStatusChange: string;
		budgetThresholdPercent: string;
		deadlineAlertDays: string;
		save: string;
	};
	auth: {
		login: string;
		emailAddress: string;
		emailPlaceholder: string;
		password: string;
		passwordPlaceholder: string;
		forgotPassword: string;
		loginButton: string;
		resetPassword: string;
		resendCode: string;
		backToLogin: string;
		confirmCode: string;
		setNewPassword: string;
		confirmPassword: string;
		passwordChanged: string;
		passwordChangedMessage: string;
		changePasswordButton: string;
		recovery: string;
		ofPassword: string;
		enterEmailDescription: string;
		enterCode: string;
		codeSentTo: string;
		codeSent: string;
		codeSendFailed: string;
	};
	validation: {
		required: string;
		shortRequired: string;
		passwordMismatch: string;
		tvaInvalid: string;
		minLength: (n: number) => string;
		maxLength: (n: number) => string;
		phoneFormat: string;
		emailInvalid: string;
		passwordMinLength: (n: number) => string;
		dateRequired: (label: string) => string;
		invalidDateFormat: string;
	};
	errors: {
		errorOccurred: string;
		errorApology: string;
		authRequired: string;
		pageNotFound: string;
		pageNotFoundText: string;
		accessDenied: string;
		accessDeniedText: string;
		maintenanceTitle: string;
		maintenanceText: string;
		maintenanceSuspended: string;
		maintenanceThanks: string;
		maintenanceChip: string;
		deletionError: string;
		globalError: string;
		serverError: string;
		networkCheckMessage: string;
		unauthorized: string;
		authRequiredDetail: string;
		networkError: string;
		cannotConnectServer: string;
		genericError: string;
		sessionExpired: string;
		serviceUnavailable: string;
		unknownError: string;
		unexpectedError: string;
	};
	notFound: {
		title: string;
		message: string;
		backBtn: string;
		homeBtn: string;
	};
	pdf: {
		generatePdf: string;
		chooseLanguage: string;
		french: string;
		english: string;
	};
	rawData: {
		genders: {
			male: string;
			female: string;
		};
		projectStatuses: {
			completed: string;
			inProgress: string;
			notStarted: string;
			onHold: string;
		};
		fieldLabels: {
			project: Record<string, string>;
			category: Record<string, string>;
			revenue: Record<string, string>;
			expense: Record<string, string>;
		};
	};
	projects: {
		projectsList: string;
		newProject: string;
		editProject: string;
		projectDetails: string;
		deleteProject: string;
		deleteProjectConfirm: string;
		projectDeletedSuccess: string;
		projectDeleteError: string;
		projectAddedSuccess: string;
		projectAddError: string;
		projectUpdatedSuccess: string;
		projectUpdateError: string;
		projectNotFound: string;
		noProjectFound: string;
		searchProjects: string;
		bulkDeleteProjects: (n: number) => string;
		bulkDeleteProjectsConfirm: string;
		bulkProjectsDeletedSuccess: (n: number) => string;
		bulkProjectsDeleteError: string;
		projectName: string;
		noStatusFound: string;
		projectInfo: string;
		clientInfo: string;
		financialInfo: string;
		budget: string;
		dateDebut: string;
		dateFin: string;
		daysRemaining: string;
		projectManager: string;
		clientName: string;
		clientPhone: string;
		clientEmail: string;
		totalRevenue: string;
		totalExpenses: string;
		profit: string;
		margin: string;
	};
	categories: {
		categoriesList: string;
		newCategory: string;
		editCategory: string;
		categoryDetails: string;
		deleteCategory: string;
		deleteCategoryConfirm: string;
		categoryDeletedSuccess: string;
		categoryDeleteError: string;
		categoryAddedSuccess: string;
		categoryAddError: string;
		categoryUpdatedSuccess: string;
		categoryUpdateError: string;
		noCategoryFound: string;
		searchCategories: string;
		bulkDeleteCategories: (n: number) => string;
		bulkDeleteCategoriesConfirm: string;
		bulkCategoriesDeletedSuccess: (n: number) => string;
		bulkCategoriesDeleteError: string;
		categoryName: string;
	};
	revenues: {
		revenuesList: string;
		newRevenue: string;
		editRevenue: string;
		revenueDetails: string;
		deleteRevenue: string;
		deleteRevenueConfirm: string;
		revenueDeletedSuccess: string;
		revenueDeleteError: string;
		revenueAddedSuccess: string;
		revenueAddError: string;
		revenueUpdatedSuccess: string;
		revenueUpdateError: string;
		revenueNotFound: string;
		searchRevenues: string;
		bulkDeleteRevenues: (n: number) => string;
		bulkDeleteRevenuesConfirm: string;
		bulkRevenuesDeletedSuccess: (n: number) => string;
		bulkRevenuesDeleteError: string;
		revenueNumber: string;
	};
	expenses: {
		expensesList: string;
		newExpense: string;
		editExpense: string;
		expenseDetails: string;
		deleteExpense: string;
		deleteExpenseConfirm: string;
		expenseDeletedSuccess: string;
		expenseDeleteError: string;
		expenseAddedSuccess: string;
		expenseAddError: string;
		expenseUpdatedSuccess: string;
		expenseUpdateError: string;
		expenseNotFound: string;
		searchExpenses: string;
		bulkDeleteExpenses: (n: number) => string;
		bulkDeleteExpensesConfirm: string;
		expensesBulkDeletedSuccess: (n: number) => string;
		expenseBulkDeleteError: string;
		expenseNumber: string;
		supplier: string;
		subCategory: string;
		noSubCategoryFound: string;
		element: string;
		categoryInfo: string;
	};
	metadata: {
		loginTitle: string;
		loginDescription: string;
		resetPasswordTitle: string;
		usersListTitle: string;
		usersListDescription: string;
		newUserTitle: string;
		newUserDescription: string;
		userDetailsTitle: string;
		userDetailsDescription: string;
		editUserTitle: string;
		editUserDescription: string;
		editProfileTitle: string;
		editProfileDescription: string;
		changePasswordTitle: string;
		changePasswordDescription: string;
		notificationsTitle: string;
		notificationsDescription: string;
		homeTitle: string;
		homeDescription: string;
		appTitle: string;
		enterCodeTitle: string;
		enterCodeDescription: string;
		setNewPasswordTitle: string;
		setNewPasswordDescription: string;
		passwordChangedTitle: string;
		passwordChangedDescription: string;
		projectsListTitle: string;
		projectsListDescription: string;
		newProjectTitle: string;
		newProjectDescription: string;
		projectDetailsTitle: string;
		projectDetailsDescription: string;
		editProjectTitle: string;
		editProjectDescription: string;
		categoriesListTitle: string;
		categoriesListDescription: string;
		newCategoryTitle: string;
		newCategoryDescription: string;
		editCategoryTitle: string;
		editCategoryDescription: string;
		revenuesListTitle: string;
		revenuesListDescription: string;
		newRevenueTitle: string;
		newRevenueDescription: string;
		revenueDetailsTitle: string;
		revenueDetailsDescription: string;
		editRevenueTitle: string;
		editRevenueDescription: string;
		expensesListTitle: string;
		expensesListDescription: string;
		newExpenseTitle: string;
		newExpenseDescription: string;
		expenseDetailsTitle: string;
		expenseDetailsDescription: string;
		editExpenseTitle: string;
		editExpenseDescription: string;
	};
	analytics: {
		overviewTitle: string;
		totalProjects: string;
		totalBudget: string;
		totalRevenue: string;
		totalExpenses: string;
		totalProfit: string;
		profitMargin: string;
		budgetUtilisation: string;
		projectBreakdown: string;
		budgetVsActual: string;
		budgetVsActualSub: string;
		profitByProject: string;
		profitByProjectSub: string;
		statusDistribution: string;
		statusDistributionSub: string;
		noDataAvailable: string;
		budget: string;
		revenue: string;
		expenses: string;
		profit: string;
	};
	accessibility: {
		toggleDrawer: string;
		moreActions: string;
	};
};
